# Configuration file for the JustTowers plugin

towers:
  number: 16 # Number of towers to generate in the world
  spacing: 16 # Distance between each tower in blocks (along the X-axis)
  height: 20 # Height of each tower in blocks
  material: BEDROCK # Material used to generate the towers (e.g., BEDROCK, STONE, OBSIDIAN)

gameplay:
  item-interval: 10 # Time interval (in seconds) for giving random items to players
  rising-speed: 1 # Lower values mean faster rising (e.g., 1 block every 2 seconds = 0.5)
  water-damage: 2.0 # Damage per second dealt by water if the mode is "Rising Water"

voting:
  enable-mode-voting: true # Enable or disable voting for the rising mode (lava, water, void)
  enable-biome-voting: true # Enable or disable voting for the biome (overworld, nether, end)
  default-mode: void # Default rising mode if voting is disabled (options: lava, water, void)
  default-biome: overworld # Default biome if voting is disabled (options: overworld, nether, end)