#      ██╗  ████████╗
#      ██║  ╚══██╔══╝
#      ██║     ██║
# ██   ██║     ██║
# ╚█████╔╝     ██║
#  ╚════╝      ╚═╝
# Configuration file for the JustTowers plugin
# Supports RGB color codes (e.g., &b for light blue, &c for red) and MiniMessage format for advanced formatting

# General plugin settings
general:
  prefix: "&b&l[Towers] " # Prefix for all plugin messages (supports & color codes or MiniMessage)
  language: "en_US" # Language file to use (e.g., en_US, cs_CZ, custom file in plugins/JustTowers/languages/)

# Tower generation settings
towers:
  number: 8 # Number of towers to generate (1-32 recommended, min: 1, max: 64)
  radius: 16.0 # Base radius of the tower circle (min: 8.0, max: 100.0)
  gap: 5.0 # Additional gap between towers (min: 2.0, max: 20.0)
  bottom_y: 64 # Starting Y level for towers (min: -64, max: 320, default: 64 for overworld)
  height:
    min: 20 # Minimum height of each tower (min: 5, max: 100)
    max: 20 # Maximum height of each tower (min: min_height, max: 100)
  materials: # List of materials for tower generation (randomly selected if multiple)
    - BEDROCK # Primary material (e.g., BEDROCK, STONE, OBSIDIAN)

# Gameplay settings
gameplay:
  item:
    interval: 10 # Time interval for giving random items to players (min: 1, max: 300)
  rising:
    speed: 1.0 # Blocks per second the rising mechanic moves (0.1 = fast, 2.0 = slow, min: 0.1)
    damage: 2.0 # Damage per second from rising mechanic (e.g., water/lava, min: 0.0, max: 20.0)
  border:
    shrink-interval: 15 # Time interval for border shrinking in Border mode (min: 5, max: 300)
    initial-size: 64.0 # Initial border size (min: 16.0, max: 500.0)
    min-size: 8.0 # Minimum border size after shrinking (min: 4.0)
  start:
    player-count: 2 # Minimum players to start the game (min: 1, max: 100)
    countdown: 30 # Countdown timer before game starts (in seconds, min: 10, max: 120)

# Voting settings
voting:
  enabled:
    mode: true # Enable voting for rising mode (true/false)
    biome: true # Enable voting for biome (true/false)
  defaults:
    mode: "void" # Default rising mode if voting disabled (options: lava, water, void, border)
    biome: "overworld" # Default biome if voting disabled (options: overworld, nether, end)
  vote-duration: 30 # Duration of voting period (in seconds, min: 10, max: 120)