name: JustTowers
version: '1.0.1-Alpha'
main: dev.rokyytr.JustTowers
api-version: '1.21'
authors: [RokyYTR]
description: Just a towers plugin
commands:
  towers:
    description: Manage the Towers minigame
    usage: /<command> <setup|tp|join|leave|reload>
permissions:
  towers.setup:
    description: Setup for Towers game
    default: op
  towers.tp:
    description: Teleports you to Towers game
    default: op
  towers.join:
    description: Joins you to Towers game
    default: true
  towers.reload:
    description: Reload the plugin configuration
    default: op